export const projetos=[
    {
      id:1,
      nome: "Aluroni",
      descricao: " Projeto Front-end de site de restaurante italiano \n\n  Recursos do aplicativo:\n\n - Acessar informações sobre cada prato\n\n- Filtrar pratos por categoria\n\n- Buscar pratos por nome\n\n- Ordenar pratos por preço, porção ou quantidade de pessoas servidas",
      imagem: "/images/aluroni.png",
      github: "https://github.com/Mariahsth/aluroni",
      demo: "https://aluroni-snowy.vercel.app/",
      tags:"React, TypeScript, Node.js, Jest",
    },
    {
      id:2,
      nome: "ByteBank",
      descricao: " Página de cotação de moedas em tempo real\n\n  Recursos do aplicativo:\n\n- Acessar em tempo real a cotação em reais de dólar, euro e iene \n\n- Interface gráfica e valores da moeda atualizados a cada 5 segundos",
      imagem: "/images/byte-bank.jpg",
      github: "https://github.com/Mariahsth/byte-bank",
      demo: "https://byte-bank-two.vercel.app/",
      tags:"JS, HTML, CSS",
    },
    {
      id:3,
      nome: "Event tracker",
      descricao: " Aplicativo de calendário para agenda de eventos\n\n  Recursos do aplicativo:\n\n- Calendário interativo\n\n- Buscar eventos salvos no banco de dados\n\n- Criar novos eventos no banco de dados\n\n- Excluir eventos\n\n- Finalizar eventos\n\n- Filtro de eventos por data",
      imagem: "/images/event-tracker.png",
      github: "https://github.com/Mariahsth/event-tracker",
      demo: "https://event-tracker-ebon.vercel.app/",
      tags:"React, TypeScript, Node.js",
    },
    {
      id:4,
      nome: "Réplica do Spotify",
      descricao: " Projeto Full-stack de aplicativo web que permite acessar e ouvir as principais músicas dos artistas mais ouvidos do Brasil.\n\n  Recursos do aplicativo:\n\n- Acessar artistas e músicas populares\n\n- Acessar albuns de cada artista\n\n- Acessar player da música escolhida\n\n- Reproduzir e pausar música desejada\n\n- Seguir para a póxima música ou para a anterior\n\n- Reproduzir música no modo aleatório",
      imagem: "/images/spotify.jpg",
      github: "https://github.com/Mariahsth/spotify",
      demo: "https://spotify-o6op.onrender.com/",
      tags:"Node.js, JS, React, Express, MongoDB, Axios, Vite",
    },
    {
      id:5,
      nome: "Alurabooks",
      descricao: " Aplicativo de livraria\n\n  Recursos do aplicativo:\n\n",
      imagem: "/images/alurabooks.png",
      github: "https://github.com/Mariahsth/alurabooks-react",
      demo: "https://alurabooks-gamma-liart.vercel.app/#",
      tags:"React, CSS, JS",
    },
    {
      id:6,
      nome: "Fokus",
      descricao: " Aplicativo interativo de controle de tarefas\n\n  Recursos do aplicativo:\n\n- Interface temática interativa: Foco, Descanso curto ou descanso longo\n\n- Cronometragem de acordo com o tema\n\n- Reprodução e pausa de música\n\n- Inclusão de atividade na lista de tarefas\n\n- Edição e exclusão de tarefa\n\n- Seleção de tarefa em andamento\n\n- Finalização de tarefa ao final do cronometro",
      imagem: "/images/fokus.png",
      github: "https://github.com/Mariahsth/projeto_Fokus",
      demo: "https://projeto-fokus-hazel.vercel.app/",
      tags:"HTML, CSS, JS",
    },
    {
      id:7,
      nome: "Amigo Secreto",
      descricao: " Sorteador de amigo secreto\n\n  Recursos do aplicativo:\n\n- Controle mínimo de participantes\n\n- Controle de nomes repetidos\n\n- Sorteio de amigo secreto\n\n- Projeto com testes unitários",
      imagem: "/images/amigo-secreto.png",
      github: "https://github.com/Mariahsth/amigo-secreto-jest/tree/main",
      demo: "https://amigo-secreto-jest-4r2g.vercel.app/",
      tags:"React, TypeScript, Node.js, Jest, CSS",
    },

  ]
  